/* eslint-disable @typescript-eslint/no-require-imports -- React Native static asset requires */
import type { ImageSourcePropType } from 'react-native';

export type AppImageSource = ImageSourcePropType;

export const images = {
  app: {
    icon: require('./app/icon.png') as AppImageSource,
    adaptiveIcon: require('./app/adaptive-icon.png') as AppImageSource,
    splash: require('./app/splash.png') as AppImageSource,
    favicon: require('./app/favicon.png') as AppImageSource,
  },
  brand: {
    logoMark: require('./brand/logo-mark.png') as AppImageSource,
    logoFullAr: require('./brand/logo-full-ar.png') as AppImageSource,
    logoFullEn: require('./brand/logo-full-en.png') as AppImageSource,
    logoFullBilingual: require('./brand/logo-full-bilingual.png') as AppImageSource,
    logoWhite: require('./brand/logo-white.png') as AppImageSource,
    logoDark: require('./brand/logo-dark.png') as AppImageSource,
  },
  onboarding: {
    university: require('./onboarding/onboarding-university.png') as AppImageSource,
    verification: require('./onboarding/onboarding-verification.png') as AppImageSource,
    groups: require('./onboarding/onboarding-groups.png') as AppImageSource,
    filesPrinting: require('./onboarding/onboarding-files-printing.png') as AppImageSource,
  },
  verification: {
    studentCardGuide: require('./verification/student-card-guide.png') as AppImageSource,
    cardExampleGood: require('./verification/card-example-good.png') as AppImageSource,
    cardExampleBlurry: require('./verification/card-example-blurry.png') as AppImageSource,
    cardExampleCropped: require('./verification/card-example-cropped.png') as AppImageSource,
    cardExampleDark: require('./verification/card-example-dark.png') as AppImageSource,
    pending: require('./verification/verification-pending.png') as AppImageSource,
    approved: require('./verification/verification-approved.png') as AppImageSource,
    rejected: require('./verification/verification-rejected.png') as AppImageSource,
  },
  emptyStates: {
    announcements: require('./empty-states/empty-announcements.png') as AppImageSource,
    subjects: require('./empty-states/empty-subjects.png') as AppImageSource,
    groups: require('./empty-states/empty-groups.png') as AppImageSource,
    files: require('./empty-states/empty-files.png') as AppImageSource,
    printingOrders: require('./empty-states/empty-printing-orders.png') as AppImageSource,
    notifications: require('./empty-states/empty-notifications.png') as AppImageSource,
    supportTickets: require('./empty-states/empty-support-tickets.png') as AppImageSource,
    chat: require('./empty-states/empty-chat.png') as AppImageSource,
  },
  errors: {
    network: require('./errors/error-network.png') as AppImageSource,
    server: require('./errors/error-server.png') as AppImageSource,
    permission: require('./errors/error-permission.png') as AppImageSource,
    sessionExpired: require('./errors/error-session-expired.png') as AppImageSource,
    maintenance: require('./errors/error-maintenance.png') as AppImageSource,
  },
  printing: {
    hero: require('./printing/printing-hero.png') as AppImageSource,
    orderPending: require('./printing/order-pending.png') as AppImageSource,
    orderProcessing: require('./printing/order-processing.png') as AppImageSource,
    orderReady: require('./printing/order-ready.png') as AppImageSource,
    orderCompleted: require('./printing/order-completed.png') as AppImageSource,
    orderCancelled: require('./printing/order-cancelled.png') as AppImageSource,
  },
  files: {
    pdf: require('./files/file-pdf.png') as AppImageSource,
    image: require('./files/file-image.png') as AppImageSource,
    document: require('./files/file-document.png') as AppImageSource,
    locked: require('./files/file-locked.png') as AppImageSource,
    previewError: require('./files/file-preview-error.png') as AppImageSource,
  },
  notifications: {
    announcement: require('./notifications/notification-announcement.png') as AppImageSource,
    verification: require('./notifications/notification-verification.png') as AppImageSource,
    printing: require('./notifications/notification-printing.png') as AppImageSource,
    support: require('./notifications/notification-support.png') as AppImageSource,
    group: require('./notifications/notification-group.png') as AppImageSource,
  },
  illustrations: {
    studentMale: require('./illustrations/student-male.png') as AppImageSource,
    studentFemale: require('./illustrations/student-female.png') as AppImageSource,
    studyDesk: require('./illustrations/study-desk.png') as AppImageSource,
    universityBuilding: require('./illustrations/university-building.png') as AppImageSource,
    success: require('./illustrations/success.png') as AppImageSource,
    warning: require('./illustrations/warning.png') as AppImageSource,
    search: require('./illustrations/search.png') as AppImageSource,
  },
} as const;

export type EmptyStateImageKey = keyof typeof images.emptyStates;
export type ErrorImageKey = keyof typeof images.errors;
export type FileImageKey = keyof typeof images.files;
export type NotificationImageKey = keyof typeof images.notifications;
export type PrintingImageKey = keyof typeof images.printing;
export type VerificationImageKey = keyof typeof images.verification;

export const expectedImageAssetPaths = [
  'src/assets/app/icon.png',
  'src/assets/app/adaptive-icon.png',
  'src/assets/app/splash.png',
  'src/assets/app/favicon.png',
  'src/assets/brand/logo-mark.png',
  'src/assets/brand/logo-full-ar.png',
  'src/assets/brand/logo-full-en.png',
  'src/assets/brand/logo-full-bilingual.png',
  'src/assets/brand/logo-white.png',
  'src/assets/brand/logo-dark.png',
  'src/assets/onboarding/onboarding-university.png',
  'src/assets/onboarding/onboarding-verification.png',
  'src/assets/onboarding/onboarding-groups.png',
  'src/assets/onboarding/onboarding-files-printing.png',
  'src/assets/verification/student-card-guide.png',
  'src/assets/verification/card-example-good.png',
  'src/assets/verification/card-example-blurry.png',
  'src/assets/verification/card-example-cropped.png',
  'src/assets/verification/card-example-dark.png',
  'src/assets/verification/verification-pending.png',
  'src/assets/verification/verification-approved.png',
  'src/assets/verification/verification-rejected.png',
  'src/assets/empty-states/empty-announcements.png',
  'src/assets/empty-states/empty-subjects.png',
  'src/assets/empty-states/empty-groups.png',
  'src/assets/empty-states/empty-files.png',
  'src/assets/empty-states/empty-printing-orders.png',
  'src/assets/empty-states/empty-notifications.png',
  'src/assets/empty-states/empty-support-tickets.png',
  'src/assets/empty-states/empty-chat.png',
  'src/assets/errors/error-network.png',
  'src/assets/errors/error-server.png',
  'src/assets/errors/error-permission.png',
  'src/assets/errors/error-session-expired.png',
  'src/assets/errors/error-maintenance.png',
  'src/assets/printing/printing-hero.png',
  'src/assets/printing/order-pending.png',
  'src/assets/printing/order-processing.png',
  'src/assets/printing/order-ready.png',
  'src/assets/printing/order-completed.png',
  'src/assets/printing/order-cancelled.png',
  'src/assets/files/file-pdf.png',
  'src/assets/files/file-image.png',
  'src/assets/files/file-document.png',
  'src/assets/files/file-locked.png',
  'src/assets/files/file-preview-error.png',
  'src/assets/notifications/notification-announcement.png',
  'src/assets/notifications/notification-verification.png',
  'src/assets/notifications/notification-printing.png',
  'src/assets/notifications/notification-support.png',
  'src/assets/notifications/notification-group.png',
  'src/assets/illustrations/student-male.png',
  'src/assets/illustrations/student-female.png',
  'src/assets/illustrations/study-desk.png',
  'src/assets/illustrations/university-building.png',
  'src/assets/illustrations/success.png',
  'src/assets/illustrations/warning.png',
  'src/assets/illustrations/search.png',
] as const;
